# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  
variables:
  rgname: "inlineyamlrg"
  location: "westus"

steps:
- task: AzurePowerShell@5
  displayName: Az powershell yaml inline
  inputs:
    azureSubscription: 'AzureConnection'
    ScriptType: 'InlineScript'
    Inline: |
     new-azresourcegroup -name $(rgname) -location $(location)
    azurePowerShellVersion: 'LatestVersion'
